apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger:9411/api/v1/spans"
  metric:
    enabled: true
  logging:
    level: "info"
    outputPaths: [ "stdout" ]
    errorOutputPaths: [ "stderr" ]

---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-jaeger-config
  namespace: monitoring
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger:9411/api/v1/spans"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.46
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: SPAN_STORAGE_TYPE
          value: "memory"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - port: 5775
      protocol: UDP
      targetPort: 5775
    - port: 6831
      protocol: UDP
      targetPort: 6831
    - port: 6832
      protocol: UDP
      targetPort: 6832
    - port: 5778
      protocol: TCP
      targetPort: 5778
    - port: 16686
      protocol: TCP
      targetPort: 16686
    - port: 14268
      protocol: TCP
      targetPort: 14268
    - port: 9411
      protocol: TCP
      targetPort: 9411
  type: LoadBalancer