#!/bin/bash
# Task: T5.6.2 - Deploy Prometheus and Grafana Monitoring Stack
# Constitution: v5.0 compliant | Phase 5 Specification: v1.0
# Generated by: cicd-monitoring-agent

set -e

echo "=========================================="
echo "Deploying Prometheus and Grafana"
echo "Task: T5.6.2"
echo "=========================================="
echo ""

# Get the absolute path to the monitoring directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MONITORING_DIR="$SCRIPT_DIR"

echo "Step 1: Creating monitoring namespace..."
kubectl apply -f "$MONITORING_DIR/prometheus/namespace.yaml"
echo "✓ Namespace created"
echo ""

echo "Step 2: Deploying Prometheus..."
kubectl apply -f "$MONITORING_DIR/prometheus/prometheus-config.yaml"
kubectl apply -f "$MONITORING_DIR/prometheus/prometheus-deployment.yaml"
kubectl apply -f "$MONITORING_DIR/prometheus/prometheus-service.yaml"
echo "✓ Prometheus deployed"
echo ""

echo "Step 3: Deploying ServiceMonitors (optional - requires Prometheus Operator)..."
kubectl apply -f "$MONITORING_DIR/prometheus/servicemonitor.yaml" 2>/dev/null || echo "⚠ ServiceMonitor CRDs not available (Prometheus Operator not installed)"
echo ""

echo "Step 4: Deploying Grafana..."
kubectl apply -f "$MONITORING_DIR/grafana/grafana-datasource.yaml"
kubectl apply -f "$MONITORING_DIR/grafana/grafana-dashboards-configmap.yaml"
kubectl apply -f "$MONITORING_DIR/grafana/grafana-deployment.yaml"
kubectl apply -f "$MONITORING_DIR/grafana/grafana-service.yaml"
echo "✓ Grafana deployed"
echo ""

echo "Step 5: Waiting for pods to be ready..."
kubectl wait --for=condition=ready pod -l app=prometheus -n monitoring --timeout=120s
kubectl wait --for=condition=ready pod -l app=grafana -n monitoring --timeout=120s
echo "✓ All pods are ready"
echo ""

echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
echo "Access Prometheus:"
echo "  kubectl port-forward -n monitoring svc/prometheus 9090:9090"
echo "  Then open: http://localhost:9090"
echo ""
echo "Access Grafana:"
echo "  kubectl port-forward -n monitoring svc/grafana 3000:3000"
echo "  Then open: http://localhost:3000"
echo "  Default credentials: admin / admin123"
echo ""
echo "Verify deployment:"
echo "  kubectl get pods -n monitoring"
echo "  kubectl get svc -n monitoring"
echo ""
echo "View logs:"
echo "  kubectl logs -n monitoring -l app=prometheus"
echo "  kubectl logs -n monitoring -l app=grafana"
echo ""
echo "=========================================="
