#!/bin/bash
# Task: T5.6.1 - Docker Image Build Script
# Generated by: cicd-monitoring-agent
# Reference: phase5-spec.md Section 6.1, constitution.md Section 6

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DOCKER_REGISTRY="${DOCKER_REGISTRY:-docker.io}"
DOCKER_USERNAME="${DOCKER_USERNAME:-}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
GIT_SHA="${GIT_SHA:-$(git rev-parse --short HEAD)}"

# Image names
BACKEND_IMAGE="${DOCKER_USERNAME}/todo-backend"
FRONTEND_IMAGE="${DOCKER_USERNAME}/todo-frontend"
WORKER_IMAGE="${DOCKER_USERNAME}/reminder-worker"

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed"
        exit 1
    fi

    if [ -z "$DOCKER_USERNAME" ]; then
        log_error "DOCKER_USERNAME environment variable is not set"
        exit 1
    fi

    log_info "Prerequisites check passed"
}

build_backend() {
    log_info "Building backend image..."

    docker build \
        -t "${BACKEND_IMAGE}:${IMAGE_TAG}" \
        -t "${BACKEND_IMAGE}:${GIT_SHA}" \
        -f backend/Dockerfile \
        backend/

    log_info "Backend image built successfully"
}

build_frontend() {
    log_info "Building frontend image..."

    docker build \
        -t "${FRONTEND_IMAGE}:${IMAGE_TAG}" \
        -t "${FRONTEND_IMAGE}:${GIT_SHA}" \
        -f frontend/Dockerfile \
        frontend/

    log_info "Frontend image built successfully"
}

build_worker() {
    log_info "Building reminder worker image..."

    if [ -f backend/Dockerfile.worker ]; then
        docker build \
            -t "${WORKER_IMAGE}:${IMAGE_TAG}" \
            -t "${WORKER_IMAGE}:${GIT_SHA}" \
            -f backend/Dockerfile.worker \
            backend/
    else
        log_warn "Dockerfile.worker not found, using main Dockerfile"
        docker build \
            -t "${WORKER_IMAGE}:${IMAGE_TAG}" \
            -t "${WORKER_IMAGE}:${GIT_SHA}" \
            -f backend/Dockerfile \
            backend/
    fi

    log_info "Worker image built successfully"
}

push_images() {
    log_info "Pushing images to registry..."

    docker push "${BACKEND_IMAGE}:${IMAGE_TAG}"
    docker push "${BACKEND_IMAGE}:${GIT_SHA}"

    docker push "${FRONTEND_IMAGE}:${IMAGE_TAG}"
    docker push "${FRONTEND_IMAGE}:${GIT_SHA}"

    docker push "${WORKER_IMAGE}:${IMAGE_TAG}"
    docker push "${WORKER_IMAGE}:${GIT_SHA}"

    log_info "All images pushed successfully"
}

list_images() {
    log_info "Built images:"
    docker images | grep -E "(todo-backend|todo-frontend|reminder-worker)"
}

# Main execution
main() {
    log_info "Starting Docker image build process..."
    log_info "Registry: ${DOCKER_REGISTRY}"
    log_info "Username: ${DOCKER_USERNAME}"
    log_info "Tag: ${IMAGE_TAG}"
    log_info "Git SHA: ${GIT_SHA}"

    check_prerequisites

    build_backend
    build_frontend
    build_worker

    list_images

    # Push images if PUSH_IMAGES is set to true
    if [ "${PUSH_IMAGES:-false}" = "true" ]; then
        push_images
    else
        log_warn "Skipping image push (set PUSH_IMAGES=true to push)"
    fi

    log_info "Build process completed successfully!"
}

# Run main function
main "$@"
