#!/bin/bash
# Task: T5.6.1 - Deployment Script
# Generated by: cicd-monitoring-agent
# Reference: phase5-spec.md Section 6.1, constitution.md Section 6

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
ENVIRONMENT="${1:-staging}"
NAMESPACE="todo-${ENVIRONMENT}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
HELM_TIMEOUT="${HELM_TIMEOUT:-5m}"

# Image names
BACKEND_IMAGE="${DOCKER_USERNAME}/todo-backend:${IMAGE_TAG}"
FRONTEND_IMAGE="${DOCKER_USERNAME}/todo-frontend:${IMAGE_TAG}"
WORKER_IMAGE="${DOCKER_USERNAME}/reminder-worker:${IMAGE_TAG}"

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v kubectl &> /dev/null; then
        log_error "kubectl is not installed"
        exit 1
    fi

    if ! command -v helm &> /dev/null; then
        log_error "helm is not installed"
        exit 1
    fi

    # Check kubectl connection
    if ! kubectl cluster-info &> /dev/null; then
        log_error "Cannot connect to Kubernetes cluster"
        exit 1
    fi

    log_info "Prerequisites check passed"
}

create_namespace() {
    log_step "Creating namespace ${NAMESPACE}..."

    if kubectl get namespace "${NAMESPACE}" &> /dev/null; then
        log_info "Namespace ${NAMESPACE} already exists"
    else
        kubectl create namespace "${NAMESPACE}"
        log_info "Namespace ${NAMESPACE} created"
    fi
}

deploy_backend() {
    log_step "Deploying backend to ${ENVIRONMENT}..."

    local REPLICA_COUNT=1
    if [ "${ENVIRONMENT}" = "production" ]; then
        REPLICA_COUNT=3
    fi

    helm upgrade --install todo-backend ./charts/todo-backend \
        --namespace "${NAMESPACE}" \
        --set image.repository="${DOCKER_USERNAME}/todo-backend" \
        --set image.tag="${IMAGE_TAG}" \
        --set environment="${ENVIRONMENT}" \
        --set replicaCount="${REPLICA_COUNT}" \
        --wait \
        --timeout "${HELM_TIMEOUT}"

    log_info "Backend deployed successfully"
}

deploy_frontend() {
    log_step "Deploying frontend to ${ENVIRONMENT}..."

    local REPLICA_COUNT=1
    if [ "${ENVIRONMENT}" = "production" ]; then
        REPLICA_COUNT=3
    fi

    helm upgrade --install todo-frontend ./charts/todo-frontend \
        --namespace "${NAMESPACE}" \
        --set image.repository="${DOCKER_USERNAME}/todo-frontend" \
        --set image.tag="${IMAGE_TAG}" \
        --set environment="${ENVIRONMENT}" \
        --set replicaCount="${REPLICA_COUNT}" \
        --wait \
        --timeout "${HELM_TIMEOUT}"

    log_info "Frontend deployed successfully"
}

deploy_worker() {
    log_step "Deploying reminder worker to ${ENVIRONMENT}..."

    local REPLICA_COUNT=1
    if [ "${ENVIRONMENT}" = "production" ]; then
        REPLICA_COUNT=2
    fi

    helm upgrade --install reminder-worker ./charts/todo-backend \
        --namespace "${NAMESPACE}" \
        --set image.repository="${DOCKER_USERNAME}/reminder-worker" \
        --set image.tag="${IMAGE_TAG}" \
        --set worker.enabled=true \
        --set replicaCount="${REPLICA_COUNT}" \
        --wait \
        --timeout "${HELM_TIMEOUT}"

    log_info "Worker deployed successfully"
}

wait_for_pods() {
    log_step "Waiting for pods to be ready..."

    kubectl wait --for=condition=ready pod \
        -l app=todo-backend \
        -n "${NAMESPACE}" \
        --timeout=300s || log_warn "Backend pods not ready yet"

    kubectl wait --for=condition=ready pod \
        -l app=todo-frontend \
        -n "${NAMESPACE}" \
        --timeout=300s || log_warn "Frontend pods not ready yet"

    log_info "Pods are ready"
}

show_deployment_status() {
    log_step "Deployment status:"

    echo ""
    log_info "Pods:"
    kubectl get pods -n "${NAMESPACE}"

    echo ""
    log_info "Services:"
    kubectl get services -n "${NAMESPACE}"

    echo ""
    log_info "Ingress:"
    kubectl get ingress -n "${NAMESPACE}" 2>/dev/null || log_warn "No ingress found"
}

rollback_deployment() {
    log_error "Deployment failed! Rolling back..."

    helm rollback todo-backend -n "${NAMESPACE}" || true
    helm rollback todo-frontend -n "${NAMESPACE}" || true
    helm rollback reminder-worker -n "${NAMESPACE}" || true

    log_info "Rollback completed"
}

# Main execution
main() {
    log_info "Starting deployment to ${ENVIRONMENT}..."
    log_info "Namespace: ${NAMESPACE}"
    log_info "Image tag: ${IMAGE_TAG}"

    # Trap errors and rollback
    trap rollback_deployment ERR

    check_prerequisites
    create_namespace
    deploy_backend
    deploy_frontend
    deploy_worker
    wait_for_pods
    show_deployment_status

    log_info "Deployment to ${ENVIRONMENT} completed successfully!"

    if [ "${ENVIRONMENT}" = "production" ]; then
        log_warn "Production deployment completed. Monitor logs for the next 5 minutes."
    fi
}

# Validate environment argument
if [[ ! "${ENVIRONMENT}" =~ ^(staging|production)$ ]]; then
    log_error "Invalid environment: ${ENVIRONMENT}"
    echo "Usage: $0 <staging|production>"
    exit 1
fi

# Run main function
main "$@"
