#!/bin/bash
# Task: T5.6.4 - Test Alerts Script
# Implements: phase5-spec.md Section 7.4 (Alerting)
# Generated by: cicd-monitoring-agent
# Date: 2026-02-15

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
NAMESPACE="${NAMESPACE:-todo-app}"
PROMETHEUS_URL="${PROMETHEUS_URL:-http://localhost:9090}"
ALERTMANAGER_URL="${ALERTMANAGER_URL:-http://localhost:9093}"

# Print colored message
print_message() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

# Print section header
print_header() {
    echo ""
    print_message "$BLUE" "=========================================="
    print_message "$BLUE" "$1"
    print_message "$BLUE" "=========================================="
    echo ""
}

# Check if Prometheus is accessible
check_prometheus() {
    print_header "Checking Prometheus Connectivity"

    if curl -s "${PROMETHEUS_URL}/-/healthy" > /dev/null 2>&1; then
        print_message "$GREEN" "✓ Prometheus is accessible at ${PROMETHEUS_URL}"
        return 0
    else
        print_message "$RED" "✗ Prometheus is not accessible at ${PROMETHEUS_URL}"
        print_message "$YELLOW" "Hint: Run 'kubectl port-forward -n monitoring svc/prometheus 9090:9090' in another terminal"
        return 1
    fi
}

# Check if Alertmanager is accessible
check_alertmanager() {
    print_header "Checking Alertmanager Connectivity"

    if curl -s "${ALERTMANAGER_URL}/-/healthy" > /dev/null 2>&1; then
        print_message "$GREEN" "✓ Alertmanager is accessible at ${ALERTMANAGER_URL}"
        return 0
    else
        print_message "$RED" "✗ Alertmanager is not accessible at ${ALERTMANAGER_URL}"
        print_message "$YELLOW" "Hint: Run 'kubectl port-forward -n monitoring svc/alertmanager 9093:9093' in another terminal"
        return 1
    fi
}

# List all configured alert rules
list_alert_rules() {
    print_header "Listing Configured Alert Rules"

    local rules=$(curl -s "${PROMETHEUS_URL}/api/v1/rules" | jq -r '.data.groups[].rules[] | select(.type=="alerting") | .name' 2>/dev/null)

    if [ -n "$rules" ]; then
        print_message "$GREEN" "Configured alert rules:"
        echo "$rules" | while read -r rule; do
            echo "  - $rule"
        done
    else
        print_message "$RED" "✗ No alert rules found"
        return 1
    fi
}

# Check current alert status
check_alert_status() {
    print_header "Checking Current Alert Status"

    local alerts=$(curl -s "${PROMETHEUS_URL}/api/v1/alerts" | jq -r '.data.alerts[] | "\(.labels.alertname) - \(.state)"' 2>/dev/null)

    if [ -n "$alerts" ]; then
        print_message "$YELLOW" "Current alerts:"
        echo "$alerts" | while read -r alert; do
            echo "  - $alert"
        done
    else
        print_message "$GREEN" "✓ No alerts currently firing"
    fi
}

# Send test alert to Alertmanager
send_test_alert() {
    local alert_name=$1
    local severity=$2
    local summary=$3
    local description=$4

    print_header "Sending Test Alert: $alert_name"

    local payload=$(cat <<EOF
[{
  "labels": {
    "alertname": "$alert_name",
    "severity": "$severity",
    "service": "test-service",
    "category": "test"
  },
  "annotations": {
    "summary": "$summary",
    "description": "$description",
    "runbook": "https://docs.todo-app.com/runbooks/test",
    "dashboard": "https://grafana.todo-app.com/d/test"
  },
  "startsAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "endsAt": "$(date -u -d '+5 minutes' +%Y-%m-%dT%H:%M:%SZ)"
}]
EOF
)

    local response=$(curl -s -X POST "${ALERTMANAGER_URL}/api/v1/alerts" \
        -H "Content-Type: application/json" \
        -d "$payload")

    if echo "$response" | jq -e '.status == "success"' > /dev/null 2>&1; then
        print_message "$GREEN" "✓ Test alert sent successfully"
        print_message "$YELLOW" "Check your notification channels (email, Slack, etc.) for the alert"
    else
        print_message "$RED" "✗ Failed to send test alert"
        echo "Response: $response"
        return 1
    fi
}

# Test high error rate alert
test_high_error_rate() {
    send_test_alert \
        "TestHighErrorRate" \
        "critical" \
        "Test: High error rate detected" \
        "This is a test alert for high error rate (>5%)"
}

# Test high latency alert
test_high_latency() {
    send_test_alert \
        "TestHighLatency" \
        "warning" \
        "Test: High latency detected" \
        "This is a test alert for high latency (p95 > 1000ms)"
}

# Test service down alert
test_service_down() {
    send_test_alert \
        "TestServiceDown" \
        "critical" \
        "Test: Service is down" \
        "This is a test alert for service down"
}

# Test high CPU usage alert
test_high_cpu() {
    send_test_alert \
        "TestHighCPUUsage" \
        "warning" \
        "Test: High CPU usage detected" \
        "This is a test alert for high CPU usage (>80%)"
}

# Test high memory usage alert
test_high_memory() {
    send_test_alert \
        "TestHighMemoryUsage" \
        "critical" \
        "Test: High memory usage detected" \
        "This is a test alert for high memory usage (>90%)"
}

# Test Kafka consumer lag alert
test_kafka_lag() {
    send_test_alert \
        "TestHighKafkaConsumerLag" \
        "warning" \
        "Test: High Kafka consumer lag" \
        "This is a test alert for Kafka consumer lag (>1000 messages)"
}

# Test Dapr sidecar unhealthy alert
test_dapr_unhealthy() {
    send_test_alert \
        "TestDaprSidecarUnhealthy" \
        "critical" \
        "Test: Dapr sidecar unhealthy" \
        "This is a test alert for unhealthy Dapr sidecar"
}

# Verify alert rules are loaded
verify_alert_rules() {
    print_header "Verifying Alert Rules Configuration"

    local expected_rules=(
        "HighErrorRate"
        "HighLatency"
        "ServiceDown"
        "HighCPUUsage"
        "HighMemoryUsage"
        "HighKafkaConsumerLag"
        "DaprSidecarUnhealthy"
    )

    local all_found=true

    for rule in "${expected_rules[@]}"; do
        if curl -s "${PROMETHEUS_URL}/api/v1/rules" | jq -e ".data.groups[].rules[] | select(.name==\"$rule\")" > /dev/null 2>&1; then
            print_message "$GREEN" "✓ Alert rule found: $rule"
        else
            print_message "$RED" "✗ Alert rule not found: $rule"
            all_found=false
        fi
    done

    if [ "$all_found" = true ]; then
        print_message "$GREEN" "✓ All expected alert rules are configured"
        return 0
    else
        print_message "$RED" "✗ Some alert rules are missing"
        return 1
    fi
}

# Check Alertmanager configuration
check_alertmanager_config() {
    print_header "Checking Alertmanager Configuration"

    local config=$(curl -s "${ALERTMANAGER_URL}/api/v1/status" | jq -r '.data.config' 2>/dev/null)

    if [ -n "$config" ]; then
        print_message "$GREEN" "✓ Alertmanager configuration loaded"

        # Check for configured receivers
        local receivers=$(echo "$config" | jq -r '.receivers[].name' 2>/dev/null)
        if [ -n "$receivers" ]; then
            print_message "$GREEN" "Configured receivers:"
            echo "$receivers" | while read -r receiver; do
                echo "  - $receiver"
            done
        fi
    else
        print_message "$RED" "✗ Failed to retrieve Alertmanager configuration"
        return 1
    fi
}

# Run all tests
run_all_tests() {
    print_header "Running All Alert Tests"

    local failed=0

    check_prometheus || ((failed++))
    check_alertmanager || ((failed++))
    list_alert_rules || ((failed++))
    verify_alert_rules || ((failed++))
    check_alertmanager_config || ((failed++))
    check_alert_status

    echo ""
    print_message "$YELLOW" "Sending test alerts..."
    sleep 2

    test_high_error_rate || ((failed++))
    sleep 1
    test_high_latency || ((failed++))
    sleep 1
    test_service_down || ((failed++))
    sleep 1
    test_high_cpu || ((failed++))
    sleep 1
    test_high_memory || ((failed++))
    sleep 1
    test_kafka_lag || ((failed++))
    sleep 1
    test_dapr_unhealthy || ((failed++))

    echo ""
    if [ $failed -eq 0 ]; then
        print_message "$GREEN" "=========================================="
        print_message "$GREEN" "✓ All tests passed successfully!"
        print_message "$GREEN" "=========================================="
        return 0
    else
        print_message "$RED" "=========================================="
        print_message "$RED" "✗ $failed test(s) failed"
        print_message "$RED" "=========================================="
        return 1
    fi
}

# Show usage
show_usage() {
    cat <<EOF
Usage: $0 [COMMAND]

Test alerting configuration for Todo AI Chatbot

Commands:
    all                     Run all tests (default)
    check                   Check connectivity and configuration
    list                    List all configured alert rules
    status                  Check current alert status
    verify                  Verify alert rules are loaded

    high-error-rate         Test high error rate alert
    high-latency            Test high latency alert
    service-down            Test service down alert
    high-cpu                Test high CPU usage alert
    high-memory             Test high memory usage alert
    kafka-lag               Test Kafka consumer lag alert
    dapr-unhealthy          Test Dapr sidecar unhealthy alert

Environment Variables:
    PROMETHEUS_URL          Prometheus URL (default: http://localhost:9090)
    ALERTMANAGER_URL        Alertmanager URL (default: http://localhost:9093)
    NAMESPACE               Kubernetes namespace (default: todo-app)

Examples:
    # Run all tests
    $0 all

    # Check connectivity only
    $0 check

    # Test specific alert
    $0 high-error-rate

    # Use custom URLs
    PROMETHEUS_URL=http://prometheus.example.com $0 all

EOF
}

# Main script
main() {
    local command=${1:-all}

    case "$command" in
        all)
            run_all_tests
            ;;
        check)
            check_prometheus
            check_alertmanager
            ;;
        list)
            list_alert_rules
            ;;
        status)
            check_alert_status
            ;;
        verify)
            verify_alert_rules
            ;;
        high-error-rate)
            test_high_error_rate
            ;;
        high-latency)
            test_high_latency
            ;;
        service-down)
            test_service_down
            ;;
        high-cpu)
            test_high_cpu
            ;;
        high-memory)
            test_high_memory
            ;;
        kafka-lag)
            test_kafka_lag
            ;;
        dapr-unhealthy)
            test_dapr_unhealthy
            ;;
        help|--help|-h)
            show_usage
            exit 0
            ;;
        *)
            print_message "$RED" "Unknown command: $command"
            echo ""
            show_usage
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
